### ISSUE TITLE
Repo is created 40 minutes ago and is already on Google on irrelevant search query - just fun fact

### ISSUE THREAD

**Issue by Kenya-West** [soroushmirzaei/telegram-configs-collector#12]
I just typed `get all channels links i am subscribed telegram github` in Google and got your brand new repo in results, despite it is 40 minutes old.

Lol.

<details><summary>Details</summary>
<p>

![image](https://github.com/soroushmirzaei/telegram-configs-collector/assets/12271104/d64d4589-4060-4b6a-b99c-239ed26d5b52)

</p>
</details> 

It is just a fun fact issue, and not an issue at all I guess...

**Comment by Kenya-West** [comment]
And by the way, how did you get 230 stars in just 40 minutes?..

**Comment by soroushmirzaei** [comment]
This is because after running the code on Github Action, the push and commit commands are performed in a scheduled manner while deleting all previous commits. This is why you see only one commit on the main page of the repository, but at the bottom of the main page in the statistics section, you can see the process of receiving stars over time.
