### ISSUE TITLE
Nekobox crashes when i try to run URI test TLS-SUBSCRIPTION

### ISSUE THREAD

**Issue by firestarter7924** [soroushmirzaei/telegram-configs-collector#2]
Nekobox just closes. Don't know why. Maybe bad server in the list.

**Comment by soroushmirzaei** [comment]
In fact, this issue is not related to this repository, and it just collects configurations from subscription links and Telegram channels and resolve destination, and if the app doesn't cover anything in the configuration, it will not import it. But you can change a few things and check their effect. In this application, you can check the effect of changing TUN Implementation, Resolve Destination, and FakeDNS settings. Otherwise, make sure you are using the latest released version of the app. notice, the huge amout of imported configrations may sometimes cause crashing the app while the testing. otherwise if the problem is not solved, you can report the issue in the NekoBox repository by attaching the log file.
